### ISSUE TITLE
Sponsorblock segments persisting over multiple videos and erroneously skipping

### ISSUE THREAD

**Issue by Atemu** [polymorphicshade/NewPipe#16]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open video with sponsored segments
2. Keep video player open and select another video (e.g. from recommendations)

### Actual behaviour

There is a sponsorblock segment bar at the same time stamp as the previous video, even if the new one shouldn't have any.

When trying to play these segments, they are skipped.

The segments persisting visually has been a bug for so long that I've gotten used to it but the skipping is new and was introduced in 0.20.6.  

This bug has appeared once in the past too but it was fixed not long after.

### Expected behavior

The new video should only have its own sponsorblock segments shown and skipped.

### Device info

 - Android version/Custom ROM version: Homebrewed LOS17.1
 - Device model: cheeseburger

**Comment by polymorphicshade** [comment]
Oh jeez I know what happened... in my attempt to make things async I screwed up how segments are stored.
This should be an easy fix, hopefully I don't end up making things buggier than Cyberpunk 2077.

**Comment by polymorphicshade** [comment]
This should now be fixed in release [v0.20.6_r2](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.6_r2) (see commit 53f9e6b).

**Comment by Atemu** [comment]
Can confirm it is no longer skipping erroneously like it did before.

I can still get the segments to persist visually though. It's very inconsistent (just like before) but after a few videos, you'll have the SB segments where there shouldn't be any.

I think I found the pattern: I could get it to reproduce when switching from a video with sponsored segments to one that has none.

**Comment by suburbanbourbon** [comment]
I am able to reproduce this issue when playing video from a playlist or a queue.

E.g., (you may take any two or more videos that have sponsor segments)
Video 1 [This video will not age well... - AMD Radeon RX 7900 Series Review](https://www.youtube.com/watch?v=TBJ-vo6Ri9c)
![Screenshot_20221220-211458](https://user-images.githubusercontent.com/85622842/208712855-1ff609f3-5983-40ac-ad08-89f7936ee262.jpg)

Video 2 [I made my own RAM! - Micron Factory Tour](https://www.youtube.com/watch?v=-EhDlXx3okU)
![Screenshot_20221220-211515](https://user-images.githubusercontent.com/85622842/208712982-67c8bcd0-8a0f-47cc-9365-6c97a273869b.jpg)

When playing Video 1 before Video 2. Video 1's UI segments persist when playing Video 2. But the segments
![Screenshot_20221220-211633](https://user-images.githubusercontent.com/85622842/208713721-8242de34-6ee7-425f-b8d7-4ff315132247.jpg)

I haven't created a new issue for this because of the bug report guideline checklist.
